server:
  port: ${port:8005}
spring:
  application:
    name: xifu-auth
  jackson: # 空值不返回
      default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    password: 123456
# 注册到eureka中
eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaServiceUrl:http://127.0.0.1:7001/eureka/}
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true